export interface FlatRecord {
     id?: string;
     market?: string;
     offerId: string | number;
     offerIdExpected: string | number;
     offerType: string;
     offerStatus: string;
     dateAdded: Date;
     dateChanged?: Date;
     dateUpdated: Date;
     dateEndTransaction?: Date;
     localization: string;
     street?: string;
     lawStatus?: string;
     price: number;
     priceOffer?: number;
     priceSold?: number;
     rent?: number;
     priceM2?: number;
     livingArea?: number;
     material?: string;
     buildingType?: string;
     yearBuilt?: number;
     floorsNumber?: number;
     buildingQuality?: string;
     flatQuality?: string;
     floor?: number;
     balcony?: string;
     balconyQuantity?: number;
     terracesQuantity?: number;
     loggiasQuantity?: number;
     frenchBalconyQuantity?: number;
     roomsNumber?: number;
     kitchenType?: string;
     basement?: string;
     storageRoom?: string;
     attic?: string;
     parkingPlace?: string;
     priceParkingUnderground?: number;
     priceParkingGround?: number;
     garden?: string;
     elevator?: string;
     security?: string;
     monitoring?: string;
     guardedArea?: string;
     securityControl?: string;
     description: string;

     balconyLemma?: string;
     elevatorLemma?: string;
     basementLemma?: string;
     garageLemma?: string;
     gardenLemma?: string;
     modernizationLemma?: string;
     monitoringLemma?: string;
     lawStatusLemma?: string;
     kitchenLemma?: string;
     technologyLemma?: string;
     outbuildingLemma?: string;
     rentLemma?: string;
     streetLemma?: string;
}

export type FlatsListResponse = FlatRecord[];
export type OneFlatResponse = FlatRecord